### ISSUE TITLE
Issue with  looseApplication = false?

### ISSUE THREAD

**Issue by hrstoyanov** [WASdev/ci.gradle#166]
I noticed an issue with installing the app as ```looseApplication= false``` (using 2.0.1 and Gradle 4.3.1):
```
server {
         ...
        looseApplication= false
    }
```
Basically ```installApp``` task fails with :
```
java.nio.file.NoSuchFileException: C:\temp\gitlab\recres\recres-webapp\build\libs\recres-webapp-1.0.0-SNAPSHOT.war -> C:\temp\gitlab\recres\recres-webapp\build\wlp\usr\servers\recres_server\apps\recres-webapp.war
```
. The workaround I found was to first deploy with  ```looseApplication= true``` then manually go and delete the generated XML app file in the server, and then switch back to  ```looseApplication= false``` 

Has anyone else seen this issue?

**Comment by jjvilleg** [comment]
This turned out to be an issue with a task output change in gradle 4.3.

**Comment by hrstoyanov** [comment]
Awesome! When can we get a build in maven with this fix in?

**Comment by cthigh** [comment]
The fix is available in the 2.0.2-SNAPSHOT on OSS.  A new point release should be out within a couple weeks.

**Comment by hrstoyanov** [comment]
Thank you! I will use the snapshots for now.

**Comment by hrstoyanov** [comment]
Hm ... I still have the same issue with 2.0.2-SNAPSHOT. Was it put back for some reason?

**Comment by cthigh** [comment]
@jjvilleg, I got an email from @hrstoyanov replying to this thread that he is still seeing this issue on the 2.0.2-SNAPSHOT.  @hrstoyanov, can you make sure you have indeed downloaded the latest snapshot by using the Gradle `--refresh-dependencies` option. We have observed Gradle not downloading the latest snapshot.

**Comment by hrstoyanov** [comment]
@cthigh will re-try it on Monday, where I can run it on a Windows 7 computer. I do not see the issue on Mac, so it maybe Gradle cache issue. Thanks!
Btw, Gradle released 4.4

**Comment by hrstoyanov** [comment]
could not reproduce the issue, please disregard.

**Comment by hrstoyanov** [comment]
@jjvilleg @cthigh @mattbsox 
Well, I spoke too soon... The issue is there even with the latest 2.1-SNAPSHOT and here is some clue:
The problem seems to that **apps** subfolder does not exist in the error message I reported:
```Groovy
Caused by: java.nio.file.NoSuchFileException: C:\temp\gitlab\recres\recres-webapp\build\libs\recres-webapp-1.0.0-SNAPSHOT.war -> C:\temp\gitlab\recres\recres-webapp\build\wlp\usr\servers\defaultServer\apps\recres-webapp.war
        at net.wasdev.wlp.gradle.plugins.tasks.InstallAppsTask.installProjectArchive(InstallAppsTask.groovy:77)
        at net.wasdev.wlp.gradle.plugins.tasks.InstallAppsTask.installProject(InstallAppsTask.groovy:121)
        at net.wasdev.wlp.gradle.plugins.tasks.InstallAppsTask$_installMultipleApps_closure1.doCall(InstallAppsTask.groovy:72)
        at net.wasdev.wlp.gradle.plugins.tasks.InstallAppsTask.installMultipleApps(InstallAppsTask.groovy:71)
        at net.wasdev.wlp.gradle.plugins.tasks.InstallAppsTask.installApps(InstallAppsTask.groovy:52)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        ... 41 more

```


When I manually create ```C:\temp\gitlab\recres\recres-webapp\build\wlp\usr\servers\defaultServer\apps``` all works fine. The stack trace above indicate that you should make sure all sub-paths exist, before attempting to copy the WAR:

```groovy
    private void installProjectArchive(Task task, String appsDir){
      Files.copy(task.archivePath.toPath(), new File(getServerDir(project), "/" + appsDir + "/" + getArchiveName(task)).toPath(), StandardCopyOption.REPLACE_EXISTING)
      validateAppConfig(getArchiveName(task), task.baseName, appsDir)
    }
```

My expectation was that in the sequence:
```
gradlew -p recres-webapp clean installLiberty libertyCreate installApps
```
this would all be taken care of, but is not? Here are my extra dependencies - **am I missing something**?

```
clean.dependsOn 'libertyStop'
undeploySharedLibs.dependsOn 'libertyStop'
deploySharedlibs.dependsOn 'installApps'
libertyStart.dependsOn  'deploySharedlibs'
```

**Comment by jjvilleg** [comment]
Hi, I ran the https://github.com/WASdev/sample.servlet with looseApplication set to false on both windows and mac with Gradle version 4.3.1 and the latest 2.1 release of our plugin. I was not able to replicate the issue. How are you configuring your liberty closure in the build.gradle?

**Comment by hrstoyanov** [comment]
```groovy
apply plugin: 'war'
apply plugin: 'liberty'
apply plugin: 'fr.putnami.gwt'

putnami {

    module gwt_app_modules
    gwtVersion = gwt_version
    gwtServletLib = false
    gwtElementalLib = false

    compile {
        strict = true
        logLevel = gwt_log_level /** The level of logging detail (ERROR, WARN, INFO, TRACE, DEBUG, SPAM, ALL) */
        compileReport = false
        optimize = gwt_compiler_optimize
        draftCompile = gwt_compiler_draft_compile
        checkAssertions = false
        style = gwt_compiler_style
        sourceLevel = java_lang_level
        minHeapSize = gwt_compiler_minHeapSize
        maxHeapSize = gwt_compiler_maxHeapSize
        localWorkers = 2
    }

    dev {
        strict = true             /** shown all compile errors */
        noServer = true           /** disable this internal server */
        bindAddress = server_host /** The ip address of the code server. */
        failOnError = false
        precompile = false
        port = 9876
        //sourceLevel = java_lang_level
        logLevel = gwt_dev_log_level

        /** Java args */
        minHeapSize = gwt_compiler_minHeapSize
        maxHeapSize = gwt_compiler_maxHeapSize
    }

}

configurations{
    errai { transitive = true }
    odb { transitive = true }
}


dependencies {

    //GWT compile
    //providedCompile ("com.peruncs.gwt:gwt-stripe:${gwt_stripe_version}") 
    //providedCompile ("com.peruncs.gwt:gwt-utils:${gwt_utils_version}") 
    providedCompile("com.peruncs.gwt:gwt-errai:${gwt_errai_version}")
    providedCompile("com.peruncs.gwt:gwt-uikit:${gwt_uikit_version}")

    //Java EE
    providedCompile("javax:javaee-api:${java_ee_version}")

    //Guava
    providedCompile ("com.google.guava:guava-gwt:${guava_version}")

    //Elemental2
    providedCompile "com.google.jsinterop:base:${jsinterop_base_version}"
    //providedCompile "com.google.elemental2:elemental2-core:${gwt_elemental2_version}"
    //providedCompile "com.google.elemental2:elemental2-dom:${gwt_elemental2_version}"

    //Errai
    providedCompile "org.jboss.errai:errai-ioc:${errai_version}"
    providedCompile "org.jboss.errai:errai-cdi-client:${errai_version}"
    providedCompile "org.jboss.errai:errai-data-binding:${errai_version}"
    providedCompile "org.jboss.errai:errai-jaxrs-client:${errai_version}"
    providedCompile "org.jboss.errai:errai-ui:${errai_version}"
    providedCompile "org.jboss.errai:errai-navigation:${errai_version}"
    providedCompile  "org.slf4j:slf4j-api:${slf4j_version}"
    providedCompile "com.google.guava:guava:${guava_version}"

    //OrientDB
    providedCompile "com.orientechnologies:orientdb-server:${odb_version}"
    providedCompile "com.orientechnologies:orientdb-distributed:${odb_version}"
    providedCompile "com.orientechnologies:orientdb-graphdb:${odb_version}"
    providedCompile "com.orientechnologies:orientdb-object:${odb_version}"
    providedCompile "com.orientechnologies:orientdb-client:${odb_version}"


    //Errai OpenLiberty  shared lib dependencies
    errai "org.jboss.errai:errai-cdi-server:${errai_version}"
    errai "org.jboss.errai:errai-jaxrs-provider:${errai_version}"
    errai "org.jboss.errai:errai-ioc:${errai_version}"
    errai "org.jboss.errai:errai-cdi-client:${errai_version}"
    errai "org.jboss.errai:errai-data-binding:${errai_version}"
    errai "org.jboss.errai:errai-jaxrs-client:${errai_version}"
    errai "org.jboss.errai:errai-ui:${errai_version}"
    errai "org.jboss.errai:errai-navigation:${errai_version}"
    errai "org.jboss.errai:errai-cdi-server:${errai_version}"
    errai "org.jboss.errai:errai-jaxrs-provider:${errai_version}"

    errai "com.google.gwt:gwt-user:${gwt_version}"
    errai "org.slf4j:slf4j-api:${slf4j_version}"
    errai "com.google.guava:guava:${guava_version}"

    //OrientDB
    odb "com.orientechnologies:orientdb-server:${odb_version}"
    odb "com.orientechnologies:orientdb-distributed:${odb_version}"
    odb "com.orientechnologies:orientdb-graphdb:${odb_version}"
    odb "com.orientechnologies:orientdb-object:${odb_version}"
    odb "com.orientechnologies:orientdb-client:${odb_version}"









    //OpenLiberty
    libertyRuntime "io.openliberty:openliberty-runtime:${openliberty_version}"
    //libertyRuntime "com.ibm.websphere.appserver.runtime:wlp-webProfile7:${openliberty_version}"

}


//Exclude GWT classes
war {
    rootSpec.exclude('**/com/recres/web/gwt/client/')
}



liberty {
    server {
        //name = 'recres'
        apps = [war]
        stripVersion = true
        looseApplication = false
//        features {
//            acceptLicense = true
//        }
    }
}

task deploySharedlibs {
    description 'Copies ERRAI,OrientDB jars into the OpenLiberty shared libs folder.'
    doLast {
        copy {
            from configurations.errai
            exclude '**/utils*.jar',
                    //Gwt
                    '**/elemental2*.jar', '**/base*.jar', '**/jsinterop-annotations*.jar',
                    //Errai
                    '**/errai-ui*.jar',
                    //'errai-codegen*.jar',
                    '**/errai*client*.jar',
                    '**/errai-navigation*.jar', '**/errai-data-binding*.jar',
                    //Other
                    '**/jgroups*.jar',
                    '**/error_prone*.jar',
                    '**/guava-gwt*.jar', '**/j2objc*.jar',
                    '**/gwt-slf4j*.jar',// '**/slf4j*.jar',
                    '**/javaee*.jar', 'javax.mail*.jar', '**/activation*.jar',
                    '**/junit*.jar', '**/hamcrest-core*.jar',
                    '**/dom4j*.jar', 'xml-apis*.jar',
                    '**/lesscss*.jar', 'rhino*.jar'
            into "$buildDir/wlp/usr/servers/defaultServer/errai"
        }
        copy {
            from configurations.odb
            into "$buildDir/wlp/usr/servers/defaultServer/odb"
        }
    }
}

task undeploySharedLibs(type: Delete) {
    description 'Delete ERRAI,OrientDB jars into the OpenLiberty shared libs folder.'
    delete "$buildDir/wlp/usr/servers/defaultServer/errai", "$buildDir/wlp/usr/servers/defaultServer/odb"
}


clean.dependsOn 'libertyStop'
undeploySharedLibs.dependsOn 'libertyStop'
deploySharedlibs.dependsOn 'installLiberty'
libertyStart.dependsOn  'deploySharedlibs'
```

**Comment by jjvilleg** [comment]
The build file looks fine. Where are you setting the buildscript information? We usually add the buildscript in the build.gradle. 

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'net.wasdev.wlp.gradle.plugins:liberty-gradle-plugin:2.1'
    }
}
```
Also, have you tried ```--refresh-dependencies``` option? It could be possible that you're project is still using an older version of our plugin.

**Comment by hrstoyanov** [comment]
I keep the build script setup in the root of my project, but it is the same as yours. Also, I use the latest Gradle 4.4.1, but I doubt this is the issue.  The ``` --refresh-dependnecies``` does not help, and indeed, I have never seen the issue on my Mac.

Which of the tasks is responsible for creating the **apps** folder? Is it installLiberty? installApps ? Can there be a gap and the tasks forget to create **apps**. I guess my workaround would be to do 👍 

```
task installApp{
    doFirst {
        //create dir "$buildDir/wlp/usr/servers/defaultServer/apps
    }
}

```

**Comment by hrstoyanov** [comment]
This is my current workaround, though I don't think I should be forced to do that:
```groovy
// This is a workaround for https://github.com/WASdev/ci.gradle/issues/166
task createMissingAppsDir {
    doLast {
        new File("$buildDir/wlp/usr/servers/defaultServer/apps").mkdirs()
    }
}
installApps.dependsOn 'createMissingAppsDir'
```

**Comment by jjvilleg** [comment]
I've been trying to replicate the issue but have had no luck. I took a look at the error message 
```Caused by: java.nio.file.NoSuchFileException: C:\temp\gitlab\recres\recres-webapp\build\libs\recres-webapp-1.0.0-SNAPSHOT.war -> C:\temp\gitlab\recres\recres-webapp\build\wlp\usr\servers\defaultServer\apps\recres-webapp.war``` and I'm inclined to believe it might be a stripVersion error... Do you still get the error if you set stripVersion to true?

**Comment by hrstoyanov** [comment]
@jjvilleg  
Removing ```stripVersion=true``` does not help. Is there any way can contact you privately and give you some sample code? The issue is elusive as I only see it on my Win 7/64-bit machine.

**Comment by cthigh** [comment]
Your test case would help. Can you open a WebSphere PMR and upload the sample with the PMR?

**Comment by jjvilleg** [comment]
@hrstoyanov Do you have any updates on this issue?

**Comment by hrstoyanov** [comment]
I am sorry I did not dig into this deeper. I deployed the workaround I mentioned in this thread and never saw it again. I will loose it now

**Comment by jensengelke** [comment]
I can reproduce the issue if my server has a name other than "defaultServer".

**Comment by cthigh** [comment]
Jens requested that this issue be reopened.

**Comment by jensengelke** [comment]
I am sorry. Me, too, I am no longer able to recreate the issue in a clean new project.

In my failing project, I have been reordering tasks, which is the most likely cause.

**Comment by jjvilleg** [comment]
Is this happening on Windows or Mac @jensengelke ?

**Comment by jensengelke** [comment]
@jjvilleg I am using Windows

**Comment by cherylking** [comment]
@jensengelke @hrstoyanov The apps folder is created as a result of creating a Liberty server. The fact that it is missing could mean that your server has been corrupted in some way. Have you noticed anything else missing? I'm wary to simply add code to create the apps folder in this situation. Perhaps we should just check for the existence of the folder and if it is not found issue an error.

**Comment by hrstoyanov** [comment]
@cherylking the issue could only reproduce this on Windows 7 64-bit, never on my Mac. At some point, I did switch to ```defaultServer```, which might have masked it for me.

I will take off my workaround and see if this starts happening again on my WIndows system

**Comment by jensengelke** [comment]
@cherylking 
I have not noticed any other misbehavior - except that the "installFeature" tasks run every time. I assume, it is hard to have an output for this task

**Comment by cherylking** [comment]
@jensengelke @hrstoyanov Can this issue be closed? Code was added to create the apps folder if it does not exist via PR #247. Release 2.3 and later contain that fix.

**Comment by hrstoyanov** [comment]
I closed it
